name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.7'  # Замените на нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

    - name: Run tests and check coverage
      run: |
        coverage run -m pytest tests/test_app.py -v --maxfail=3 --disable-warnings
        coverage report
        coverage html
        # Опционально: сохраните отчет о покрытии как артефакт
        mkdir -p coverage_report
        cp -r htmlcov coverage_report
      continue-on-error: true  # Позволяет продолжать работу, даже если тесты не проходят
  
    - name: Upload coverage report
      if: always()  # Выполнится независимо от результата тестов
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_report